export const ADD_SECTIONS = 'ADD_SECTIONS';
export const CLICK_NAVI_DOT = 'CLICK_NAVI_DOT';
export const ARROW_KEY_PRESS = 'ARROW_KEY_PRESS';
export const OPEN_LINK_MODAL = 'OPEN_LINK_MODAL';
export const SAVE_IMAGE = 'SAVE_IMAGE';
export const CLOSE_LINK_MODAL = 'CLOSE_LINK_MODAL';